version: 0.2

phases:
  install:
    commands:
      - go get -u github.com/go-sql-driver/mysql
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - go build DummyApp.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - DummyApp
